sudo: false
language: c

matrix:
  include:
    - name: "Xenial build"
      os: linux
      dist: xenial
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - ninja
            - meson
            - clang-format
    - name: "masOS 10.14 build"
      os: osx
      osx_image: xcode10.2
      compiler:
        - gcc
        - clang
      addons:
        homebrew:
          packages:
            - ninja
            - meson
            - clang-format

script:
  - meson setup --prefix=/tmp _build
  - ninja -C _build
