sudo: false
language: c

os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2

env:
  - CC=gcc
  - CC=clang

addons:
  apt:
    packages:
      - meson
      - clang-format
  homebrew:
    packages:
      - ninja
      - meson
      - clang-format

script:
  - meson setup --prefix=/tmp _build
  - ninja -C _build
