sudo: false
language: python

python: 3.6

os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2

env:
  - CC=gcc
  - CC=clang

addons:
  apt:
    packages:
      - clang-format
  homebrew:
    packages:
      - ninja
      - meson
      - clang-format

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install meson; fi

script:
  - meson _build
  - ninja -C _build all
