sudo: false
language: c

os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2

env:
  - CC=gcc
  - CC=clang

addons:
  apt:
    packages:
      - clang-format
      - meson
  homebrew:
    packages:
      - ninja
      - meson
      - clang-format

script:
  - meson _build
  - ninja -C _build all
